export const FORM_BUILDER_ORDER = [
    "title",
    "introHtml",
    "person",
    "text",
    "textarea",
    "autocomplete",
    "checkbox-group",
    "radio-group",
    "date",
    "number",
    "file",
    "boolean",
    "select",
]