# Generated by Django 4.2.23 on 2025-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity",
            "0035_alter_activity_unique_together_alter_activity_type_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["supportgroup_id"], name="notifications_by_supportgroup"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["event_id"], name="notifications_by_event_id"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["recipient", "status", "type"],
                name="notifications_by_type_status",
            ),
        ),
    ]
