# Generated by Django 4.2.23 on 2025-09-30 12:32

from django.db import migrations
from django.conf import settings

from agir.activity.models import Activity


def create_partial_index(apps, schema_editor):
    types_list = ", ".join(f"'{t}'" for t in Activity.DISPLAYED_TYPES)
    sql = f"""
    CREATE INDEX CONCURRENTLY IF NOT EXISTS activity_recipient_none_idx
    ON activity_activity (recipient_id)
    WHERE status = 'U'
      AND event_id IS NULL
      AND supportgroup_id IS NULL
      AND type IN ({types_list});
    """
    schema_editor.execute(sql)


def drop_partial_index(apps, schema_editor):
    schema_editor.execute(
        "DROP INDEX CONCURRENTLY IF EXISTS activity_recipient_none_idx;"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("activity", "0036_add_event_type_and_group_indexes"),
    ]

    operations = [
        migrations.RunPython(create_partial_index, reverse_code=drop_partial_index),
    ]
