# Generated by Django 4.2.18 on 2025-04-30 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("people", "0035_alter_persontag_label_alter_qualification_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDiffusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "send_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Date à laquelle les messages vont être envoyé.",
                        verbose_name="Date d'envoie",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "message",
                    models.TextField(
                        help_text="SMS à envoyer",
                        max_length=500,
                        verbose_name="Question",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smsdiffusion_person",
                        to="people.person",
                        verbose_name="Créateur·ice",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment auquel ce message sera envoyé, si aucun segment sera envoyé à tout le monde.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smsdiffusion_segment",
                        related_query_name="notification",
                        to=settings.NUNTIUS_SEGMENT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Diffusion",
                "verbose_name_plural": "SMS Diffusion",
            },
        ),
    ]
