# Generated by Django 4.2.18 on 2025-05-07 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsdiffusion",
            name="send_date",
        ),
        migrations.AddField(
            model_name="smsdiffusion",
            name="broadcast_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smsdiffusion",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Date à laquelle les messages vont commencer à être envoyé.",
                verbose_name="Date d'envoie",
            ),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fin de l'envoi"
            ),
        ),
    ]
