# Generated by Django 4.2.18 on 2025-05-20 11:32

import agir.diffusion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("diffusion", "0002_remove_smsdiffusion_send_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsdiffusion",
            name="test_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment des personnes auxquelles envoyer des notifications de test",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to=settings.NUNTIUS_SEGMENT_MODEL,
                verbose_name="Segment",
            ),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="broadcast_id",
            field=models.IntegerField(default=0, verbose_name="Identifiant SFR"),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=agir.diffusion.models.get_default_end_date,
                help_text="Date maximale d'envoie, utile pour de grand segment, ne pas toucher si vous êtes pas sûre.",
                null=True,
                verbose_name="Date de fin de l'envoi",
            ),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="message",
            field=models.TextField(
                help_text="SMS à envoyer", max_length=500, verbose_name="Message"
            ),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment auquel ce message sera envoyé.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smsdiffusion_segment",
                related_query_name="notification",
                to=settings.NUNTIUS_SEGMENT_MODEL,
            ),
        ),
    ]
