# Generated by Django 4.2.18 on 2025-06-25 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("diffusion", "0003_smsdiffusion_test_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsdiffusion",
            name="sender",
            field=models.CharField(
                choices=[("LFI", "LFI"), ("ILB", "ILB")],
                default="LFI",
                verbose_name="Envoyer en tant que",
            ),
        ),
        migrations.AlterField(
            model_name="smsdiffusion",
            name="test_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment des personnes pour tester le SMS",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to=settings.NUNTIUS_SEGMENT_MODEL,
                verbose_name="Segment",
            ),
        ),
    ]
