# Generated by Django 4.2.23 on 2025-09-01 12:12

import agir.people.person_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0035_alter_persontag_label_alter_qualification_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="custom_fields",
            field=models.JSONField(
                default=agir.people.person_forms.models.default_custom_forms,
                help_text="⚠️ Toute modification sur l'éditeur dynamique au dessus, prendra la main sur les modifications de ce champ,pensez à sauvegarder avant de toucher à ce champ.",
                verbose_name="Champs",
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="send_answers_to",
            field=models.CharField(
                blank=True,
                help_text="Entrez une ou plusieurs adresses e-mail séparées par des virgules. Laissez vide si aucune notification n'est souhaitée.",
                max_length=900,
                validators=[agir.people.person_forms.models.validate_emails],
                verbose_name="Envoyer les réponses à",
            ),
        ),
    ]
