# Generated by Django 4.2.23 on 2025-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0036_alter_personform_custom_fields_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["role"], name="people_pers_role_id_a0b245_idx"),
        ),
    ]
