# Generated by Django 4.2.18 on 2025-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0039_alter_event_timezone_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["visibility"], name="events_visibility_index"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("visibility", "A"), _negated=True),
                fields=["visibility"],
                name="events_visibility_not_a_index",
            ),
        ),
    ]
