# Generated by Django 4.2.23 on 2025-09-04 08:12

import agir.lib.storage
import agir.lib.validators
import agir.msgs.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0036_alter_personform_custom_fields_and_more"),
        ("msgs", "0014_add_attachment_to_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroupmessage",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participant",
                to="people.person",
                verbose_name="Participant·e",
            ),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(
                storage=agir.lib.storage.PrivateMediaStorage(),
                upload_to=agir.msgs.models.message_attachment_upload_to,
                validators=[
                    agir.lib.validators.FileSizeValidator(10485760),
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "doc",
                            "docx",
                            "odt",
                            "xls",
                            "xlsx",
                            "ods",
                            "ppt",
                            "pptx",
                            "odp",
                            "png",
                            "jpeg",
                            "jpg",
                            "gif",
                        ]
                    ),
                ],
                verbose_name="Fichier",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="msgs.messageattachment",
                verbose_name="Pièce-jointe",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupmessagecomment",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="msgs.messageattachment",
                verbose_name="Pièce-jointe",
            ),
        ),
        migrations.AddIndex(
            model_name="supportgroupmessagecomment",
            index=models.Index(
                models.F("message_id"),
                models.OrderBy(models.F("created"), descending=True),
                name="message_comment_creation",
            ),
        ),
    ]
