# Generated by Django 4.2.23 on 2025-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0020_add_membership_remove_request"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supportgroup",
            index=models.Index(
                fields=["published"], name="supportgroup_published_index"
            ),
        ),
    ]
