# Generated by Django 4.2.23 on 2025-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0037_person_people_pers_role_id_a0b245_idx"),
        ("groups", "0021_add_published_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["person_id"], name="membership_person_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["supportgroup_id"], name="membership_group_idx"),
        ),
    ]
