name: Deploy to staging

on:
  push:
    branches:
      - BenjaminL/cd-workflow
  workflow_run:
    workflows: ["Tests", "Build front bundles"]
    types:
      - completed

jobs:
  deploy-staging:
    name: deploy to staging
    environment: preprod
    runs-on: ubuntu-22.04

    steps:
    - name: Clone
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'lafranceinsoumise'
        repository: 'playbooks'
        branch: 'master'
        access-token: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Setup Ansible
      uses: alex-oleshkevich/setup-ansible@v1.0.1
      with:
        version: 11.7.0

    - name: Setup SSH key
      run: |
        cd playbooks
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Setup Vault password
      run: |
        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_pass.txt
        chmod 600 ~/.vault_pass.txt

    - name: Run Ansible Playbook
      run: |
        cd playbooks
        ansible-playbook agir.yml \
          --tags deploy \
          --limit agir-preprod \
          --vault-password-file ~/.vault_pass.txt \
          --private-key ~/.ssh/id_rsa
