name: Deploy to staging

on:
  workflow_run:
    workflows: ["Tests", "Build front bundles", ]
    types:
      - completed

jobs:
  deploy-staging:
    name: deploy to staging
    environment: preprod
    runs-on: ubuntu-22.04
    steps:
    - name: Clone
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'Ben-Ji-L'
        repository: 'playbooks'
        access-token: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Setup Ansible
    # You may pin to the exact commit or the version.
    # uses: alex-oleshkevich/setup-ansible@f879ce3cf11a7315e130919a797526b0c6bfd272
      uses: alex-oleshkevich/setup-ansible@v1.0.1
      with:
        # The version of Ansible to install.
        version: 2.18.5 

    - name: deploy
      run: |
        ansible-playbooks agir.yml --tags deploy --limit agir-preprod
          